### ISSUE TITLE
Krzaczki zamiast polskich znaków pod Windows

### ISSUE THREAD

**Issue by Marcinosoft** [kodujwpythonie/koduj-w-pythonie#1]
Polskie znaki pod Windows zarówno w intro i outro nie są prezentowane poprawnie.

Wygląda na to, że pygame spodziewa się że strona kodowa źródła jest zgodna ze stroną systemu operacyjnego, czyli w przypadku polskiego systemu Windows konkretnie Windows-1250. Domyślnie kod źródłowy zapisywany jest jako UTF-8, przez co teksty zawierające polskie znaki są źle prezentowane.

Jako rozwiązanie wystarczy że na początku kodu źródłowego dopiszemy linię:

`# -*- coding: cp1250 -*- `
lub
`#encoding: cp1250`

To skonwertuje i zapisze źródło w stronie kodowej Windows-1250 i w efekcie polskie ogonki są prezentowane poprawnie.
Pewnie są też inne możliwości rozwiązania tego problemu.

**Comment by kodujwpythonie** [comment]
Dzień dobry,    prosimy o wysłanie wiadomości prywatnej na profilu facebook'owym Koduj w Pythonie, wówczas otrzyma Pan wsparcie techniczne.    Pozdrawiam serdecznie,  --  Anna Raczkowska Biuro Obsługi Klienta tel: +48 585 055 914 Biuro czynne od pon. - piątku w godz. 08.30-16.00 

LIMDESKTOKEN-3sKt1Z

**Comment by abixadamj** [comment]
Ech... ten Windows zawsze jest inny niż reszta świata ;-) Zawsze można go „nawrócić” na UTF ;-)
https://github.com/mu-editor/mu/issues/1076
