### ISSUE TITLE
Uruchamianie poza edytorem Mu

### ISSUE THREAD

**Issue by Marcinosoft** [kodujwpythonie/koduj-w-pythonie#2]
Nie wiem jak w Visual Studio Code, ale w PyCharm, czy Wing sposób podany w [https://github.com/kodujwpythonie/koduj-w-pythonie/blob/master/program_idle_pycharm_vscode_.py](url) generuje błąd.

PyCharm nie widzi (Unresolved reference) klas i obiektów: Actor, music, screen, animate, sounds, keyboard, clock

Aby umożliwić uruchamianie przykładów poza Mu należy dopisać przed kodem:
<pre><code>import pgzrun
import sys
from pgzero.builtins import *
mod = sys.modules['__main__']
</code></pre>

Następnie wszystkie wystąpienia `screen`, należy prefixować przy pomocy `mod.`, czyli: `mod.screen`

I w takim wydaniu nie ma błędów w IDE i wszystko działa poprawnie. Przykład poprawionego `program_02.py`:

<pre><code>import pgzrun
import sys
from pgzero.builtins import *
mod = sys.modules['__main__']

WIDTH = 1280
HEIGHT = 640

background_active = "corridor-01.jpg"
background_position = (0, 0)

def update():
    mod.screen.blit( background_active, background_position )

# uruchamiamy bibliotekę PygameZero
pgzrun.go()
</code></pre>

Sprawdzone na PyCharm Community oraz Wing 101.

No i oczywiście należy zainstalować PyGame Zero:
`pip install pgzero`

**Comment by abixadamj** [comment]
O, dzięki. Bazowałem na dokumentacji: https://pygame-zero.readthedocs.io/en/stable/ide-mode.html - jak widać nie można do końca niczemu dowierzać.

**Comment by abixadamj** [comment]
Ale właśnie na Atom sprawdzam:
![Zrzut ekranu z 2020-12-11 23-19-40](https://user-images.githubusercontent.com/5088643/101960289-690f9a80-3c07-11eb-860c-513321256ccf.png)

**Comment by abixadamj** [comment]
I w IDLE:
![Zrzut ekranu z 2020-12-11 23-21-09](https://user-images.githubusercontent.com/5088643/101960379-95c3b200-3c07-11eb-8feb-70e2a05a2479.png)

**Comment by Marcinosoft** [comment]
To jest tak, że to się owszem uruchamia, nawet w PyCharm, ale PyCharm krzyczy, że nie wie co to np. screen.

![obraz](https://user-images.githubusercontent.com/19069443/101997874-d1787d80-3cd4-11eb-9eaf-655a557cb6ef.png)

Narzekają na to w internecie, ale raczej nie będzie ruszone patrząc na to zgłoszenie:
[https://youtrack.jetbrains.com/issue/PY-41151](https://youtrack.jetbrains.com/issue/PY-41151)

Więc dzielę się obejściem dla lubiących PyCharma, bo w takiej wersji działa również na innych IDE.

**Comment by abixadamj** [comment]
Ale widzę, że nie robi problemów przy uruchamianiu, tylko wewnętrznie nie potrafi wczytać docstringów. Ale to nie jest w sumie wielki/żaden błąd. Wystarczy użyć innego edytora ;-) Albo przymknąć oczy ;-)

**Comment by Marcinosoft** [comment]
W zasadzie problemem jest tylko obiekt screen. Inne da się zaimportować z pgzero.builtins (poprawiłem w treści zgłoszenia).
Owszem na screen można przymknąć oko, lub po prostu zaznaczyć, aby PyCharm ignorował ten błąd, ale import pgzero.builtins warto dodać, dzięki temu PyCharm widzi referencje wszystkich obiektów/klas, działa asysta kodu (podpowiadanie właściwości/metod), poza obiektem screen.
