### ISSUE TITLE
Literówka/sklejka - najgorętszego bandu

### ISSUE THREAD

**Issue by Marcinosoft** [kodujwpythonie/koduj-w-pythonie#3]
Od przykładu program_06.py do końca, w tekście introdukcji, występuje sklejka:

"najgorętszegobandu"

a powinno być:

"najgorętszego bandu"

Może warto poprawić, bo w książce jest poprawnie.

**Comment by abixadamj** [comment]
@Marcinosoft - dzięki serdeczne! Przepraszam, że dopiero teraz.
